### ISSUE TITLE
[MC] [AsmParser] Parse arithmetic instructions

### ISSUE THREAD

**Issue by atrosinenko** [matter-labs/era-compiler-llvm#412]
Parse commutative and non-commutative arithmetic instructions, with all possible operand types, with both one and two output operands.

## The syntax that should be supported

For both commutative and non-commutative instructions, support all possible input operand types:

```asm
  add r1, r2, r3  // register
  add 42, r2, r3  // immediate integer
  add -42, r2, r3 // UPD: explicitly unsupported
  add stack[r1 + 1], r2, r3  // read from stack at absolute address
  ...
```

The list of instructions to support:
  - [x] add / sub
  - [x] and / or / xor
  - [x] shl / shr
  - [x] rol / rol
  - [x] mul / div

**Comment by akiramenai** [comment]
Please note that `-42` is not an immediate as its 2's complement representation doesn't fit into 16 bits. To add `-42` you should create a constant and use it as the first operand.

**Comment by atrosinenko** [comment]
Thank you for clarification. Meanwhile, is it syntactically permitted to use negative addends in code and stack references? If I get it right, code and stack pages both have exactly 2^16 distinct addresses, so no sign-extension is required.

**Comment by asl** [comment]
> Meanwhile, is it syntactically permitted to use negative addends in code and stack references? If I get it right, code and stack pages both have exactly 2^16 distinct addresses, so no sign-extension is required.

According to spec https://matter-labs.github.io/eravm-spec/spec.html#imm_in it seems like immediate field is unsigned. So, the values are always zero-extended. To reduce the confusion I would probably suggest making the wording explicit @akiramenai @sayon

**Comment by sayon** [comment]
Will fix the currently reported deficiencies in spec on the weekend, thank you!

Immediate field is unsigned `u16`, and when the address is computed, the components are added together with wrapping modulo 2^16.

**Comment by atrosinenko** [comment]
Missing features:
- [x] ~~swapped versions of commutative instructions (for uniformity)~~ (no opcodes assigned)
- [x] swapped versions of non-commutative instructions with two register inputs (for uniformity)
- [ ] generic stack-referring operands (tracked in #418)
- [x] reject 4-operand instructions without the second output (`mul r1, r2, r3`)

**Comment by atrosinenko** [comment]
Tests (links to the HEAD of `era-vm/asm-parser` branch):
* [`arith-commutative.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/arith-commutative.s)
* [`arith-commutative-2outs.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/arith-commutative-2outs.s)
* [`arith-non-commutative.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/arith-non-commutative.s)
* [`arith-non-commutative-2outs.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/arith-non-commutative-2outs.s)
* [`arith-modifiers.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/arith-modifiers.s)
* [`arith-instructions-errors.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/arith-instructions-errors.s)

Note that supporting all possible operand types is covered by a separate issue, see #418.
