### ISSUE TITLE
[MC][AsmParser] Parse stack manipulation instructions

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#417]
Syntax:
```
nop r0, r0, stack+=[reg+ofs]
nop stack-=[reg+ofs]
```

Spec:
 - https://matter-labs.github.io/eravm-spec/spec.html#SpAddDefinition
 - https://matter-labs.github.io/eravm-spec/spec.html#SpSubDefinition

Note that it mostly boils down to supporting stack manipulation operands.

**Comment by atrosinenko** [comment]
To be clarified (see #418).

**Comment by asl** [comment]
Introduce instruction aliases `SpAdd reg imm` / `SpSub reg imm`

**Comment by asl** [comment]
@atrosinenko Please double check and close

**Comment by atrosinenko** [comment]
Supported `nop` syntax similar to those of arithmetic instructions:
```
  nop r0, r0, stack+=[r1+42]
  nop stack-=[r1+42], r0, r0
```
Old-style single-operand `nop` syntax is NOT supported.
New aliases (SpAdd/SpSub) NOT added yet (postponed till mnemonic rename). 

Tests (links to the HEAD of `era-vm/asm-parser` branch):
* [`sp-changes.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/sp-changes.s)
* various other tests for instructions accepting stack operands
