### ISSUE TITLE
[MC][AsmParser] Parse different addressing modes

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#418]
- [x] Register (in/out): `add r1, r0, r3`
- [x] Imm (in): `add 42, r0, r3`, 16-bit unsigned
- [x] Code page, relative to GPR (in): `add code[42], r0, r3`
- [x] Const page, relative to GPR (in): `add code[42], r0, r3`
- [x] Stack page, relative to GPR (in/out): `add stack[r1+42], r0, r3`, `add stack=[r1+42], r0, r3`
- [x] Stack page, relative to GPR and SP (in/out): `add stack-[r1+42], r0, r3`
- [x] Stack page, relative to GPR and SP, with decreasing SP (in): `add stack-=[r1+42], r0, r3`
- [x] Stack page, relative to GPR and SP, with increasing SP (out): `add r3, r0, stack+=[r1+42]`

Spec: https://matter-labs.github.io/eravm-spec/spec.html#Addressing

Need to ensure forbidden forms are diagnosed

**Comment by atrosinenko** [comment]
Missing features:
- [ ] separate "const" page - mentioned in the spec but unsupported
- [ ] stack page - clarify syntax
  * should both `stack[...]` and `stack=[...]` forms be supported?
  * can addend be negative? If yes, should we support `stack[-1 + r1]` syntax (i.e. "-N + rM")?
- [ ] stack page, SP-relative
  * is the existing code correct in [AsmPrinter.cpp](https://github.com/matter-labs/compiler-llvm/blob/cf7f145558741c1d4fe6c1cd58e5816891c4348a/llvm/lib/Target/EraVM/MCTargetDesc/EraVMInstPrinter.cpp#L209)
- [ ] SP-changing stack access: is it explicitly restricted to `nop` instruction?
- [ ] improve diagnostic errors

**Comment by atrosinenko** [comment]
Is the following operand syntax documented anywhere?
* `stack[@global_var+31]` - emitted for LLVM IR like this: `store [32 x i256] %arg, [32 x i256]* @global_var`
  - relocations
* `@CPI1_0[0]` (input operand) - global constant
  - could be `code[@CPI1_0+0]` for uniformity
* SP-relative references printed by [`EraVMInstPrinter::printStackOperand`](https://github.com/matter-labs/compiler-llvm/blob/cf7f145558741c1d4fe6c1cd58e5816891c4348a/llvm/lib/Target/EraVM/MCTargetDesc/EraVMInstPrinter.cpp#L196) - I have not yet managed to make the backend emit such operands in their generic form, but it seems that SP-relative operands can **only** be printed by that function as `stack-[... - rN]` (but the comment mentions `+ reg` as per the spec)

Example:
```ll
target datalayout = "E-p:256:256-i256:256:256-S32-a:256:256"
target triple = "eravm"

@global_var = global [32 x i256] zeroinitializer

define void @array_setter([32 x i256] %arg) {
entry:
  store [32 x i256] %arg, [32 x i256]* @global_var
  ret void
}

define i256 @get_const() {
  ret i256 1234567890
}
```

**Comment by akiramenai** [comment]
* It looks like a bug (not exposed to users as the FE never produce such a store), could you kindly post the whole asm here? (I'm in the middle of a rebase).
* `@varname[index]` is what currently the assembler accepts. `code` is redundant as the symbols can't collide. @sayon @hedgar2017 do you have a preference here?
* SP relatives are broken now (from the compiler PoV). As far as I remember it's `+ reg` for an input and `- reg` for an output or vice versa which makes it unusable for codegen purpose. We feature requested to make it `+ reg` everywhere. @shamatar could we assume that it will be done in future ISA and go as if it's a plus?

**Comment by atrosinenko** [comment]
> It looks like a bug (not exposed to users as the FE never produce such a store), could you kindly post the whole asm here?

Considering `stack[@global_var + 31]`, here is a simplified test case:
```ll
target datalayout = "E-p:256:256-i256:256:256-S32-a:256:256"
target triple = "eravm"

@global_src = global [3 x i256] zeroinitializer
@global_dst = global [3 x i256] zeroinitializer

define void @copy() {
  %value = load [3 x i256], [3 x i256]* @global_src
  store [3 x i256] %value, [3 x i256]* @global_dst
  ret void
}
```

This produces the following asm:

```asm
        .text
        .file   "<stdin>"
        .globl  copy                            ; -- Begin function copy
copy:                                   ; @copy
; %bb.0:
        add     stack[@global_src], r0, stack[@global_dst]
        add     stack[@global_src+1], r0, stack[@global_dst+1]
        add     stack[@global_src+2], r0, stack[@global_dst+2]
        ret
                                        ; -- End function
        .data
        .globl  global_src                      ; @global_src
        .p2align        5
global_src:
        .zero   96

        .globl  global_dst                      ; @global_dst
        .p2align        5
global_dst:
        .zero   96

        .note.GNU-stack
        .rodata
```
(`main` branch, commit 7f924f377ad5c0f79b6c840dd2a4513fbcddd516)

**Comment by akiramenai** [comment]
Ok I see. We haven't had arrays on stack (globals are preallocated there), so the syntax is LLVM's default (with bytes converted to cells). I believe some people would prefer `@symbol[offset]` for all symbol-relative addresses and leave it for asm to resolve the memory page, but it would be hard for asm, right?
Now it looks logical to me to accept `code[@symbol+offset]`, `stack[@symbol+offset]` notation. @sayon, @hedgar2017 wdyt?

**Comment by hedgar2017** [comment]
> Ok I see. We haven't had arrays on stack (globals are preallocated there), so the syntax is LLVM's default (with bytes converted to cells). I believe some people would prefer `@symbol[offset]` for all symbol-relative addresses and leave it for asm to resolve the memory page, but it would be hard for asm, right?
> 
> Now it looks logical to me to accept `code[@symbol+offset]`, `stack[@symbol+offset]` notation. @sayon, @hedgar2017 wdyt?

LGTM!

**Comment by sayon** [comment]
Here are some clarifications:
1.  "separate "const" page - mentioned in the spec but unsupported"
The "code" and "const" pages are conceptually different because they are addressed differently. Code is addressed by instructions, so "jump 10" will jump to the 10th 8-byte instruction. However reading from 10-th const address will read 10-th 256-bit word. Maybe it would make sense to hide this information on assembly level and just provide the assembler users with a "constant memory region" for the constant pool, which will incidentally be placed on the code pages. 
2. It makes sense to me to keep both `code[...]` and `stack[...]` syntax. Another reason I see to do it is that we may add more memory types, this schema is more extensible.
3. As @akiramenai mentioned, currently SP-relative addressing (the one that does not mutate SP) is limited to `SP - ((reg mod 2^16) + imm)` and `imm` in this formula can only be non-negative. This affects both input and output operands. This addition wraps so it should be well defined to use 0xFFFFFFFF for -1. So I think we should support it. @akiramenai hope I am not missing anything here.
    
    - The sp-mutating address modes, however, differ, and it's `sp-(reg+imm)` for output, `sp+(reg+imm)` for input.  See https://matter-labs.github.io/eravm-spec/spec.html#RelSpPop and https://matter-labs.github.io/eravm-spec/spec.html#RelSpPush
    
 4.  SP-changing stack accesses are only implemented for NOPs but they should be implemented for all instructions with full addressing modes, both for inputs and outputs. There is no other way of mutating SP without doing any other action, so in the ISA redesign we came up with special instructions just to adjust SP (compiled into NOPs).

**Comment by atrosinenko** [comment]
@sayon Do I get the syntax for `reg+imm` addressing modes right?

All of the following syntax should be **accepted**:
* `stack[1]`, `stack[r1]`, `stack[r1+1]`, `stack[1+r1]`
* `stack[-1]`, `stack[r1 - 1]`, `stack[-1 + r1]` (for example, `stack[r1 - 1]` is the same as `stack[r1 + 65535]`)
  - this is merely about the syntax to accept, not semantics
  - of course, `stack[-r1]`, `stack[-r1+1]` are **rejected** as these cannot be represented in machine code
* the same syntax with `stack` replaced by `stack=` (the same as `stack`), `stack-`, `code` and `stack-=`/`stack+=` (in/out, respectively)
* immediate addends (if any) should be between -65535 and 65535, inclusive

PS: I created a separate issue #435 for tracking progress and discussing symbol-referring operands, as there should be more things to discuss there, while keeping more "self-contained" `reg+imm` addressing more or less complete.

**Comment by shamatar** [comment]
The only thing I know is that when stack-relative addressing changed there were no previous sequences emitted my compiler, but behavior of + or - is defined by compiler (basically assembler is a mere tool for compiler). So any changes are biased in compiler consistency

**Comment by asl** [comment]
> * immediate addends (if any) should be between -65535 and 65535, inclusive

Not quite. The field is 16-bit unsigned. However, since arithmetic is 2s-complement 16-bit, you can support signed 16-bit immediates as well (encoding them as unsigned). So, it could be:
 - 0 .. 65535
 - -32768 .. 32767

**Comment by akiramenai** [comment]
@asl @atrosinenko I confirmed we can assume `+reg` for in and out. We are likely to have these changes in ISA 1.6.

**Comment by atrosinenko** [comment]
@akiramenai 
> I confirmed we can assume `+reg` for in and out.

Do you mean `+imm`?

**Comment by akiramenai** [comment]
@atrosinenko `+reg` or `-[-reg]`. E.g. `add stack-[-r1+42], r0, r3`. `-reg` is what will be unsupported.
For immediates as wrap works, negative offsets could work as well.

**Comment by atrosinenko** [comment]
* the syntax for "subscript" is the same for all affected operand kinds: `[42]`, `[r1]`, `[r1 + 42]`, `[42 + r1]`, `[r1 - 42]`, `[-42 + r1]`, the two latter forms are accepted but converted to `[65494 + r1]` by the asm parser
  * the existing AsmPrinter code for `stack-[...]` was updated
* both `stack[...]` and `stack=[...]` can be used interchangeably (the former is **printed** for both)
* SP-modifying operands `stack-=[...]` and `stack+=[...]` can be used with any appropriate instruction, according to their direction (`-=` is input-only and `+=` is output-only)
* for symbolic references, see #435

Tests (links to the HEAD of `era-vm/asm-parser` branch):
* [`arith-operands.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/arith-operands.s)
* [`arith-operands-errors.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/arith-operands-errors.s)
