### ISSUE TITLE
[MC][AsmParser] Parse pointer modification instructions

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#420]
- [x] `ptr.add in1, in2, out` / `ptr.add.s in1, in2, out`
 - [x] `ptr.sub in1, in2, out` / `ptr.sub.s in1, in2, out`
 - [x] `ptr.shrink in1, in2, ou1` / `ptr.shrink.s in1, in2, ou1`
 - [x] `ptr.pack in1, in2, ou1` / `ptr.pack.s in1, in2, ou1`

 
Spec:
  - https://matter-labs.github.io/eravm-spec/spec.html#PtrAddDefinition
  - https://matter-labs.github.io/eravm-spec/spec.html#PtrSubDefinition
  - https://matter-labs.github.io/eravm-spec/spec.html#PtrShrinkDefinition
  - https://matter-labs.github.io/eravm-spec/spec.html#PtrPackDefinition

**Comment by atrosinenko** [comment]
Missing features:
- [x] `ptr.sub[.s]` instruction
- [x] ~~full support for 5 src mode x 3 dst mode operands~~ (meaningless for non-swapped variants)

**Comment by atrosinenko** [comment]
Meaningful combinations of operands work. Note that `ptr.<op>` and `ptr.<op>.s` are highly different. For the former instruction passing immediate or code operand as the first input is meaningless as these cannot be tagged as a pointer.

Tests (links to the HEAD of `era-vm/asm-parser` branch):
* [`ptr-instructions.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/ptr-instructions.s) - supported combinations
* [`ptr-instructions-errors.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/ptr-instructions-errors.s) - explicitly unsupported combinations
