### ISSUE TITLE
[MC][AsmParser] Parse storage instructions

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#421]
- [x] `log.swrite in1, in2` aliased as `sstore in1, in2`
 - [x] `log.sread in1, out` aliased as `sload in1, out`

Spec:
  - https://matter-labs.github.io/eravm-spec/spec.html#SStoreDefinition
  - https://matter-labs.github.io/eravm-spec/spec.html#SLoadDefinition

Relevant tests:
* llvm/test/MC/EraVM/asm-parser/storage.s

**Comment by atrosinenko** [comment]
Works.

**Comment by atrosinenko** [comment]
Tests (links to the HEAD of `era-vm/asm-parser` branch):
* [`storage.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/storage.s)
