### ISSUE TITLE
[MC][AsmParser] Parse event instructions

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#422]
- [x] `log.event in1, in2` aliased as `event in1, in2`
 - [x] `log.event.first in1, in2` aliased as `event.i in1, in2`
 - [x] `log.to_l1 in1, in2` aliased as `event in1, in2`
 - [x] `log.to_l1 event.first in1, in2` aliased as `event.i in1, in2`

Spec:
 - https://matter-labs.github.io/eravm-spec/spec.html#EventDefinition
 - https://matter-labs.github.io/eravm-spec/spec.html#ToL1Definition

**Comment by atrosinenko** [comment]
I rechecked the spec, and aliased instructions seem to be indeed the same...

**Comment by atrosinenko** [comment]
Should work, but not all mnemonics are named as per the specification (see tests).

**Comment by atrosinenko** [comment]
Works, but see #441.

Tests (links to the HEAD of `era-vm/asm-parser` branch):
* [`events.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/events.s)
* [`mnemonic-errors.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/mnemonic-errors.s) - rejecting invalid mnemonic suffixes
