### ISSUE TITLE
[MC][AsmParser] Parse misc instructions

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#423]
- [x] `log.precompile in1, in2, out1`
 - [x] `context.this out` / `context.caller out` / `context.code_source out` / `context.ergs_left out` / `context.sp out` / `context.get_context_u128 out` / `context.set_context_u128 out` / `context.meta out` / `context.inc_tx_num out` / `context.set_ergs_per_pubdata in`

Spec:
 -  https://matter-labs.github.io/eravm-spec/spec.html#PrecompileCallDefinition
 - https://matter-labs.github.io/eravm-spec/spec.html#ContextDefinitions

**Comment by atrosinenko** [comment]
From the spec:
```
Abstract Syntax: OpContextIncrementTxNumber
Assembly: context.inc_tx_num out
```

As far as I understand, `context.inc_tx_num` should be zero-operand instruction.

**Comment by atrosinenko** [comment]
`log.precompile` seems to have `precompile` mnemonic in current backend implementation. Supporting `context.<op>` should require adding a bit more code in EraVMAsmParser.

**Comment by atrosinenko** [comment]
Should work, but not all mnemonics are named as per the specification (see tests).

**Comment by atrosinenko** [comment]
Works, except for three mnemonics having different name in the backend and the spec (see #441).

Tests (links to the HEAD of `era-vm/asm-parser` branch):
* [`misc.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/misc.s)
* [`mnemonic-errors.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/mnemonic-errors.s) - rejecting invalid `<op>` in `context.<op>` mnemonic

Note that `context.inc_tx_num` is parsed as a no-operand instruction (see [OpContextIncrementTxNumber](https://matter-labs.github.io/eravm-spec/spec.html#OpContextIncrementTxNumber) as well as "Affected parts of VM state: only tx counter") assuming `context.inc_tx_num out` syntax mentions `out` by mistake.
