### ISSUE TITLE
[MC][AsmParser] Parse symbolic stack and const references

### ISSUE THREAD

**Issue by atrosinenko** [matter-labs/era-compiler-llvm#435]
Parse stack- and const-referring operands that mention `@symbol` instead of just using `reg+imm` for address computation (factored out of issue #418).

**Comment by asl** [comment]
Need tests, need examples

**Comment by atrosinenko** [comment]
Based on the discussion in #418, parsing of the following syntax is implemented at now:
* `@sym[r1 + 1]`, `code[@sym + r1 + 1]` for code
* `stack[@sym + r1 + 1]`, `stack=[@sym + r1 + 1]` for **absolute** stack references
* not implemented for SP-relative and SP-modifying addressing modes
* for simplicity, in `code[...]` and `stack[...]` syntax, `@sym` is only parsed as the first term of the "subscript", the remainder is parsed as always (i.e. both `code[@sym + r1 + 1]` and `code[@sym + 1 + r1]` works, but not `code[1 + @sym]`)

Tests (links to the HEAD of `era-vm/asm-parser` branch):
* [`symbolic-operands.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/symbolic-operands.s)
* [`arith-operands-errors.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/arith-operands-errors.s)

**Comment by akiramenai** [comment]
@atrosinenko, @hedgar2017, @sayon any suggestions on SP modifying syntax?

**Comment by akiramenai** [comment]
Sorry, found in #417. It looks good to me.

**Comment by asl** [comment]
@atrosinenko Please check and close
