### ISSUE TITLE
[MC][AsmParser] Check the list of supported condition codes

### ISSUE THREAD

**Issue by atrosinenko** [matter-labs/era-compiler-llvm#440]
At now, a number of conditional code names are supported across the instructions. These are short forms like `.eq`, `.le`, `.ge` as well as the longer forms mentioned in the [VM Primer](https://docs.zksync.io/zk-stack/components/zkEVM/vm-specification/vm-primer.html#modifiers) (such as `.if_eq`, `.if_le`, `.if_ge`, `.if_gt_or_eq`). The mapping of strings to `EraVMCC` constants is listed in `parseExplicitCondition` function in [EraVMAsmParser.cpp](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/lib/Target/EraVM/AsmParser/EraVMAsmParser.cpp) file ([permalink](https://github.com/matter-labs/compiler-llvm/blob/3f7cf0cf80c9d6cf3c648fb13c7a0ed8a49a7051/llvm/lib/Target/EraVM/AsmParser/EraVMAsmParser.cpp#L446) at the time of writing).

After redesigning the assembly syntax, only the shorter form is likely to remain, so `parseExplicitCondition` function should be updated accordingly.

**Comment by asl** [comment]
@sayon Will you please comment on what should be supported?

**Comment by sayon** [comment]
The longer form (like .if_eq) is unnecessary, the short forms are sufficient to us.  So, 

- eq
- lt
- gt
- ne
- ge
- le

@akiramenai @hedgar2017 do you think we should support something like `of` as an alias to `lt`?

**Comment by hedgar2017** [comment]
@sayon I dislike unnecessary aliases personally.

**Comment by akiramenai** [comment]
The issue here is that our `lt` is not quite `lt`, it's `lt` for `sub`. But it's more ISA issue than asm, we reuse flags for different purposes in different context. Whatever naming we choose, it's misleading for some instructions. Maybe we could rename `eq` -> `z` as it works like a conventional zero flag almost everywhere. Maybe, we want to rename `lt` to some single letter same as `gt` and make `xz`, `yz` suffixes to check 2 flags combinations. An abstract 2nd flag and 3rd flag with no associations with the name might be the best solution in our case.

**Comment by asl** [comment]
@akiramenai @hedgar2017 @sayon Ok, let me assign this issue to you, so you will decide on the intended functionality :)

**Comment by akiramenai** [comment]
I think we can go as @sayon said. `of` was reverted from the backend, and I'm ok to keep the things as they are.

**Comment by akiramenai** [comment]
As no one objects, I think we can close the issue.

**Comment by atrosinenko** [comment]
As this needs to be actually updated in the code (just a few lines), reopening it and assigning to myself.

**Comment by atrosinenko** [comment]
@akiramenai Is "gt or lt" predicate still used (see [encoding](https://matter-labs.github.io/eravm-spec/spec.html#encode_predicate)) and which name should it have?

**Comment by atrosinenko** [comment]
The last remaining question to clarify is: the spec on [encoding](https://matter-labs.github.io/eravm-spec/spec.html#encode_predicate) mentions 8 predicates:
```
Definition encode_predicate (p:predicate) : BITS 3 :=
  # match p with
    | IfAlways ⇒ 0
    | IfGT ⇒ 1
    | IfLT ⇒ 2
    | IfEQ ⇒ 3
    | IfGE ⇒ 4
    | IfLE ⇒ 5
    | IfNotEQ ⇒ 6
    | IfGTOrLT ⇒ 7
    end
.
```
The asm parser understands 7 of them: 6 explicit `.<code>` suffixes and an implicit `COND_NONE` if neither suffix is specified. Other patches for code emission and disassembler assume 7 possible predicates, too. Is it correct that the last condition code, `IfGTOrLT ⇒ 7`, is not used anymore?

Reassigning the task - please feel free to close it if `IfGTOrLT` is actually unused or assign it back to me if this condition code has to be accounted for.

**Comment by akiramenai** [comment]
@atrosinenko it looks like we mislead you wrt `IfGTOrLT`. It's only unused by current code generator, but we plan to keep on VM level. For now we can use `gl` mnemonic for it (or whatever name the current assembler accepts if it's more convenient), but we plan to rename our flags as it confuses even us internally. We are still discussing the final naming scheme.

**Comment by atrosinenko** [comment]
Added support of `.gtlt` predicate in #559.
