### ISSUE TITLE
[MC][AsmParser] Rename mnemonics according to the specification

### ISSUE THREAD

**Issue by atrosinenko** [matter-labs/era-compiler-llvm#441]
At now, most instructions are supported with _some_ mnemonic, but these mnemonics can differ in the public specification, pre-existing code (LLVM backend and standalone assembler) and possibly the updated spec.

This issue covers instruction mnemonics in a broad sense (for example, the `<op>` part in `context.<op>`) - those cases that can be resolved by simply changing string literals in C++ code or `*.td` files without changing any logic.

See #440 for conditional codes.

**Comment by atrosinenko** [comment]
As explained by @hedgar2017, replaced `gas` with `ergs` in asm mnemonics (not touching the intrinsic names yet): 3fc096329b94a41760333347e39d65325bbd7a21

**Comment by asl** [comment]
We will wait for the updated ISA spec to perform the rename

**Comment by asl** [comment]
@akiramenai @hedgar2017 @sayon So, what is the ultimate resolution on the assembler syntax from 1.6 ISA spec?

For example https://matter-labs.github.io/eravm-spec/spec.html#NearRetDefinition says:
```
Syntax
  ret in1
Legacy syntax
  ret.ok aliased as ret
```

How do you want to handle the legacy:
 1. Make backend produce only new variant, but let assembler accept the old one as an alias (and silently "upgrade"). So, it will be just `ret` and `ret.ok` will be treated as a mnemonic alias. Disassembler will produce new mnemonic.
 2. Make both backend and assembler support only new variant. Old one (`ret.ok`) will be rejected everywhere.

**Comment by hedgar2017** [comment]
@asl #2, let's reject all legacy.

**Comment by atrosinenko** [comment]
What is the new syntax for `.first` modifier of [`log`](https://matter-labs.github.io/eravm-spec/spec.html#EventDefinition) and [`logl1`](https://matter-labs.github.io/eravm-spec/spec.html#ToL1Definition) instructions?

**Comment by asl** [comment]
@sayon Please check the question above

**Comment by sayon** [comment]
Let's do `.f` for first. I will update it in spec tonight. CC @hedgar2017

**Comment by hedgar2017** [comment]
Hey @sayon @atrosinenko, do we have a single place listing all mnemonics to sort them all out?

**Comment by sayon** [comment]
Yes, in the isa redesign proposal, but i can make a separate summary table in spec for convenience -- been thinking about it.

**Comment by atrosinenko** [comment]
Pull-request #576 renames the mnemonics and modifiers according to the new spec. It is currently blocked because the standalone assembler doesn't understand the new syntax. #576 mostly consists of changes to tests and string literals (there are a few logic changes, but most are implemented by previous PRs that are either merged or can be merged without switching to the new assembler). 

Assuming #576 is merged, there should be no _mnemonic aliases_ (that is, two different instruction names accepting the same variants of operands and having the same encoding). Some _instruction aliases_ are kept:
* all 24 variants of NOP are understood by the MC layer (as `OpNoOp` is [encoded](https://matter-labs.github.io/eravm-spec/spec.html#encode_opcode) similar to arithmetic instructions). The spec only declares the syntax for three special cases: `incsp`, `decsp` and no-operand `nop` - these are detected and printed according to the spec. See #483 for discussion.
* `retl` and `revl` are defined as two-operand instructions (`retl reg, @label`). As `reg` is unused by near return/revert and is by convention set to `r1`, these patterns are detected and printed according to the spec (`retl @label`). See #567 for discussion.
* the no-operand aliases `ret` for `ret r1` and `rev` for `rev r1` are kept so far, as they seem useful for near control flow. See #455.
* it was discussed that warning/error should be generated when printing or emitting non-canonical versions of `nop` or `retl`/`revl` - see #577

**Comment by hedgar2017** [comment]
Hey @atrosinenko , thanks for the revamp.

We're finalizing the final changes for modifiers and will share them soon.

**Comment by akiramenai** [comment]
We've switched to new asm syntax
