### ISSUE TITLE
I introduced that duplication because I had issues with `OperandAddrMode` as the ColField. As you refactor our `td`s anyway, may I ask if it's hard to get rid of `OperandAM`?

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#482]
I introduced that duplication because I had issues with `OperandAddrMode` as the ColField. As you refactor our `td`s anyway, may I ask if it's hard to get rid of `OperandAM`?

_Originally posted by @akiramenai in https://github.com/matter-labs/era-compiler-llvm/pull/448#discussion_r1553744353_

**Comment by atrosinenko** [comment]
Refactored in #601 and #602.

**Comment by asl** [comment]
@akiramenai Will you please take a look? Is this something you had in mind?

**Comment by akiramenai** [comment]
@asl @atrosinenko 
Exactly. Thank you kindly.
