### ISSUE TITLE
test/CodeGen/EraVM/O0-pipeline.ll and test/CodeGen/EraVM/O3-pipeline.ll are broken

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#490]
These tests neither have target triple specified nor have explicit triple used in `llc` invocation. As a result, they always use host (!) triple. As a result, they fail is only EraVM backend is enabled like this:
```
llc: error: unable to get target for 'arm64-apple-darwin22.6.0', see --version and --triple
```

**Comment by akiramenai** [comment]
Will fix it soon,

@asl, @atrosinenko 
Noteworthy to say that we use `eravm` as the default triple when running `check-llvm` on CI, so you might want to set it locally as well.

**Comment by asl** [comment]
> Noteworthy to say that we use `eravm` as the default triple when running `check-llvm` on CI, so you might want to set it locally as well.

In general it is fine not to rely on some implicit things. Especially for tests it's great to be explicit as much as possible :)

**Comment by akiramenai** [comment]
@asl I agree, so I fixed.
But for instance generic codegen tests are run on the default target, and it seems that you use the system one. That was the point of my message.
