### ISSUE TITLE
Check predicate-analyzing functions in EraVMInstrInfo

### ISSUE THREAD

**Issue by atrosinenko** [matter-labs/era-compiler-llvm#555]
Check `getCCCode`, `isPredicated`, etc. functions because instruction predication was reworked as part of implementing the asm parser.

**Comment by akiramenai** [comment]
If the goal is refactoring, then the issue duplicates https://github.com/matter-labs/era-compiler-llvm/issues/516. Otherwise, according to our test suite, we haven't regressed correctness with the rework.
