### ISSUE TITLE
WE WANT FAIR ELIGIBILITY AND DISTRIBUTION!!!

### ISSUE THREAD

**Issue by Mera12341** [matter-labs/era-compiler-llvm#617]
# ZKSYNC TEAM WE WILL WAIT YOUR RESPONSE WE NEED REDISTRIBUTION, RE ELIGIBLE. WORK WITH NANSEEN TO FILTER SYBIL, YOU CAN DELAY TGE/ DECENTRALISATION IF YOU WANT WE WILL WAIT. WE WANT FAIR ELIGIBILITY DISTRIBUTION

                                             ..........                                                 ...........
                                                  .                                                            .
     
                                                                        .......   .........
                                                                 .. .                           . ..
                                                             ..                                         ..

**Comment by akiramenai** [comment]
Irrelevant to LLVM compiler.
