### ISSUE TITLE
Cherry pick upstream APInt fixes

### ISSUE THREAD

**Issue by vladimirradosavljevic** [matter-labs/era-compiler-llvm#687]
Some of the fixes are merged in #630 , but the idea is to revert that PR and to cherry pick upstream fixes to simplify rebase.
Upstream fixes for this issue:

PRs:
1. https://github.com/llvm/llvm-project/pull/80309
2. https://github.com/llvm/llvm-project/pull/104555

Commits:
1. https://github.com/llvm/llvm-project/commit/c876761f7ed8de0d30b65b5618bc9dbb8526bb68 + https://github.com/llvm/llvm-project/commit/3512bcc2e9ab06b0ae2cab78744550b515e54184
2. https://github.com/llvm/llvm-project/commit/dc831e8422cb0762e33fb41ffbdff8a6100e7d34
3. https://github.com/llvm/llvm-project/commit/246c236ff9761920f5098878aba651e2112618bf
4. https://github.com/llvm/llvm-project/commit/3b27fce960e965097c9d597b1bd35e8593121d25
5. https://github.com/llvm/llvm-project/commit/06f64e84738a6d6a55283ff5eef60c7ea9a92dac
6. https://github.com/llvm/llvm-project/commit/73d835cceca0638b7080ecf310594398e50e5206
7. https://github.com/llvm/llvm-project/commit/53c41f95db3ab3f4a5d4562fd76f7f4115c52bad
8. https://github.com/llvm/llvm-project/commit/4d97ad59f9ef4a26a52be8ff9bfcfa58d5039eb4
9. https://github.com/llvm/llvm-project/commit/7990a7e58f0656f752178f22a767c6250b6aa8dc
10. https://github.com/llvm/llvm-project/commit/adb4cfe0b61859eb0911b34c6f27eb5925cb9d94
11. https://github.com/llvm/llvm-project/commit/ce128d8fe8298e87799b5302e08bd0c6ea8ccce4 + https://github.com/llvm/llvm-project/commit/5d28678277195e0b136198323ef4afa4561f8796
12. https://github.com/llvm/llvm-project/commit/46fb225f3ac602970ebb8973a5376cd9216ba38f + https://github.com/llvm/llvm-project/commit/afa0f53f96b5563a80fbdf8c41c8153bf8cd2685

**Comment by akiramenai** [comment]
Done in https://github.com/matter-labs/era-compiler-llvm/pull/693
