### ISSUE TITLE
[EVM] Move non-trivial rematerialization from EVMSingleUseExpression to stackification algorithm

### ISSUE THREAD

**Issue by vladimirradosavljevic** [matter-labs/era-compiler-llvm#737]
In some cases, `EVMSingleUseExpression` pass is doing rematerialization of 2 instructions (`CALLDATA + PUSH`) to reduce stack pressure. This is not always profitable, since we could generate 1 stack manipulation instruction instead, like in the `tests/solidity/simple/yul_instructions/keccak256.sol` test:
```
Loop with rematerialization:
.BB0_8:                                 ; %for_body
                                        ; =>This Inner Loop Header: Depth=1
	JUMPDEST
	PUSH1 68
	CALLDATALOAD
	PUSH1 4
	CALLDATALOAD
	DUP3
	ADD
	MSTORE8
	ADD
	PUSH1 36
	CALLDATALOAD
	DUP2
	LT
	PUSH4 @.BB0_17
	JUMPI
```
```
Loop without rematerialization:
.BB0_8:                                 ; %for_body
                                        ; =>This Inner Loop Header: Depth=1
	JUMPDEST
	DUP3              <- No remat
	DUP6              <- No remat
	DUP3
	ADD
	MSTORE8
	ADD
	DUP3              <- No remat
	DUP2
	LT
	PUSH4 @.BB0_17
	JUMPI
```
Move 2 instruction rematerialization to stackification algorithm, since it should be possible to determine whether to do rematerialization or to reuse value from the stack.

**Comment by akiramenai** [comment]
Doesn't it duplicate https://github.com/matter-labs/era-compiler-llvm/issues/718 ?
Should we leave a comment there and close this one as a duplicate?

**Comment by vladimirradosavljevic** [comment]
Dup of #718.
